# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
defaults: &defaults
  adapter: postgresql
  username: postgres
  password: freedomcafe
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000

development:
  database: At_app_development
  <<: *defaults

test:
  database: At_app_test
  <<: *defaults

production:
  database: At_app_production
  <<: *defaults
